name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GO111MODULE: auto
      CONVERTAPI_SECRET: ${{ secrets.CONVERTAPI_SECRET }}
      CONVERTAPI_TOKEN: ${{ secrets.CONVERTAPI_TOKEN }}
      CONVERTAPI_APIKEY: ${{ secrets.CONVERTAPI_APIKEY }}

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.23

    - name: Install package
      run: go install

    - name: Build
      run: go build -v ./...

    - name: testing
      run: go test -v ./...