name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GO111MODULE: auto
      CONVERTAPI_SECRET: ${{ secrets.CONVERTAPI_SECRET }}
      CONVERTAPI_TOKEN: ${{ secrets.CONVERTAPI_TOKEN }}
      CONVERTAPI_APIKEY: ${{ secrets.CONVERTAPI_APIKEY }}

    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.22

    - name: Get package
      run: go get github.com/ConvertAPI/convertapi-go github.com/stretchr/testify

    - name: Get dependencies
      run: cd /home/runner/go/src/github.com/ConvertAPI/convertapi-go && go install ./...

    - name: Build
      run: cd /home/runner/go/src/github.com/ConvertAPI/convertapi-go && go build -v ./...

    - name: testing
      run: cd /home/runner/go/src/github.com/ConvertAPI/convertapi-go && go test -v ./...